apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-components
  description: A collection of all Backstage example components
spec:
  type: github
  targets:
    - https://github.com/gabicavalcante/crawler-jus/blob/master/packages/catalog-info.yaml
